name: Deploy to IPFS and Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Pin to IPFS via Pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        id: pinata
        with:
          pin-name: sports-brave-${{ github.sha }}
          path: ./dist
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}

      - name: Print IPFS CID
        run: echo "New CID is ${{ steps.pinata.outputs.hash }}"